package com.window.hook;
/* JADX INFO: This class is generated by JADX */
public final class R {

    public static final class array {
        public static final int xposed_scope = 0x7f010000;
    }

    public static final class color {
        public static final int white = 0x7f020001;
    }

    public static final class drawable {
        public static final int ic_launcher = 0x7f030000;
    }

    public static final class string {
        public static final int app_name = 0x7f040000;
    }

    public static final class style {
        public static final int AppTheme = 0x7f050000;
        public static final int BlackActionBarTitle = 0x7f050001;
        public static final int BlackTextActionBar = 0x7f050002;
    }
}
