apply plugin: "com.android.application"

android {
    namespace 'com.shadowfight.android'
    compileSdk 34
    defaultConfig {
        applicationId "com.shadowfight"
        minSdk 26
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }
    sourceSets {
        main {
            manifest.srcFile 'src/main/AndroidManifest.xml'
            java.srcDirs = ['src/main/java']
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    packagingOptions {
        exclude 'META-INF/robovm/ios/robovm.xml'
    }
}

dependencies {
    implementation project(":core")
    implementation "com.badlogicgames.gdx:gdx:${gdxVersion}"
    implementation "com.badlogicgames.gdx:gdx-backend-android:${gdxVersion}"
}
